### ISSUE TITLE
Problem with timezone LosAngeles and meetings within the next 60 minutes

### ISSUE THREAD

**Issue by kaie** [djc/awmy#27] opened 2019-03-07 10:00 UTC
Dear Dirkjan, thanks for creating the code that's used on http://arewemeetingyet.com

There seems to be a bug with the following configuration:
Timezone: LosAngeles
Date: today (for example 03/07/2019)
Time: the following hour
(look at https://www.timeanddate.com/worldclock/usa/los-angeles for the current time, change the form to use the following full hour. For example, it it's 02:01 a.m., enter 03:00 a.m. in the form.)
Repeat: bi-weekly
http://arewemeetingyet.com/Los%20Angeles/2019-03-07/03:00/b

Expected:
Form should show Next Occurrence is today (March 7), in less than 59 minutes.

Actual behavior:
Form shows next is on March 21.

**Comment by djc** [comment] 2019-03-07 10:33
Hey, thanks for the bug report. I did some quick testing but cannot reproduce: if I open http://arewemeetingyet.com/Los%20Angeles/2019-03-07/04:00/b right now (that is, this meeting is currently happening in 28 minutes), it seems to work just fine for me.

**Comment by kaie** [comment] 2019-03-07 10:39
No, it's not in 20 minutes from now. It's in 1 hour and 20 minutes from now. Please compare your time expectation with https://www.timeanddate.com/worldclock/usa/los-angeles

**Comment by kaie** [comment] 2019-03-07 10:41
The time zone difference between LA and Germany/Netherlands is currently 9 hours (not 8 hours as your link claims)

**Comment by djc** [comment] 2019-03-07 10:42
Ah, I see it now. That's problematic -- I'll see if I can have a look later today.

**Comment by djc** [comment] 2019-03-07 13:18
So the problem here seems to be that the repeating code will spool forwards too much if the given event is in the future by less than the timezone difference. In this case, because a transition happens between these two occurrences, the timezone from the next occurrence will affect this one, leading to a problem if the source and target timezones do not have the same transition moments.

**Comment by djc** [comment] 2019-03-09 20:09
Should be fixed now, in 29d13b9. Thanks for reporting!

**Closed by djc** 2019-03-09 20:09 UTC
